apiVersion: v1
kind: Service
metadata:
  name: gettasks-todo-microservice-service
  labels:
    app: gettasks-todo-microservice
spec:
  type: ClusterIP
  selector:
    app: gettasks-todo-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000