apiVersion: v1
kind: Service
metadata:
  name: microtodo-ui-service
  labels:
    app: microtodo-ui
spec:
  type: ClusterIP
  selector:
    app: microtodo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80