environment: dev
microtodoui:
  port: 80
  targetPort: 80
  replicas: 2
gettask:
  port: 80
  targetPort: 8000
  replicas: 2
deletetask:
  port: 80
  targetPort: 8000
  replicas: 2
addtask:
  port: 80
  targetPort: 8000
  replicas: 2