{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-microtodoui-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: microtodo-ui.tangi.fun
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.ingress.serviceactive }}-microtodo-ui-service
            port: 
              number: {{ .Values.microtodoui.port }}
{{- end }}
