environment: dev
ingress:
  enabled: false
microtodoui:
  port: 80
  targetPort: 80
  replicas: 2
  imagename: microtodoui
  imageversion: latest
gettask:
  port: 80
  targetPort: 8000
  replicas: 2
  imagename: gettaskstodo
  imageversion: latest
deletetask:
  port: 80
  targetPort: 8000
  replicas: 2
  imagename: deletetasktodo
  imageversion: latest
addtask:
  port: 80
  targetPort: 8000
  replicas: 2
  imagename: addaaskaodo
  imageversion: latest