environment: dev
ingress:
  enabled: True
  serviceactive: dev-blue-todoapp


keyvault:
  tenantId: "90d26b91-2a7d-4998-a059-54dd93adebf6"  # Your tenant ID

managedIdentity:
  clientId: "3d934898-7743-4c9f-8dd2-352fab7b31b7"  # From az identity list output



microtodoui:
  port: 80
  targetPort: 80
  replicas: 1
  imagename: microtodoui
  imageversion: latest
gettask:
  port: 80
  targetPort: 8000
  replicas: 1
  imagename: gettaskstodo
  imageversion: latest
deletetask:
  port: 80
  targetPort: 8000
  replicas: 1
  imagename: deletetasktodo
  imageversion: latest
addtask:
  port: 80
  targetPort: 8000
  replicas: 1
  imagename: addaaskaodo
  imageversion: latest