{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gettasks-todo-microservice-ingress
  labels:
    app.kubernetes.io/name: myingress
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: gettask.tangi.fun
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.ingress.serviceactive }}-gettasks-todo-microservice-service
            port: 
              number: {{ .Values.gettask.port }}
{{- end }}