apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-gettasks-todo-microservice-service
  labels:
    app: {{ .Values.environment }}-gettasks-todo-microservice
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.environment }}-gettasks-todo-microservice
  ports:
    - protocol: TCP
      port: {{ .Values.gettask.port }}
      targetPort: {{ .Values.gettask.targetPort }}