apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletetask-todo-microservice-deployment
  labels:
    app: deletetask-todo-microservice
spec:
   replicas: 2
   selector:
      matchLabels:
          app: deletetask-todo-microservice
   template:
     metadata:
       name: deletetask-todo-microservice-pod
       labels:
          app: deletetask-todo-microservice
     spec:
       containers:
          - name: deletetask-todo-microservice-container
            image: k8acrregistrydev.azurecr.io/deletetasktodo:latest
            ports:
              - containerPort: 8000
            env:
              - name: CONNECTION_STRING
                value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:k8sqlserverc.database.windows.net,1433;Database=k8db;Uid=sqladmin;Pwd=Password@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"                                          
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "250m"
                memory: "256Mi" 