apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deletetask-todo-pod
  labels:
    app: {{ .Release.Name }}-deletetask-todo-microservice
spec:
   replicas: {{ .Values.deletetask.replicas }}
   selector:
      matchLabels:
          app: {{ .Release.Name }}-deletetask-todo-microservice
   template:
     metadata:
       labels:
          app: {{ .Release.Name }}-deletetask-todo-microservice
     spec:
       containers:
          - name: {{ .Release.Name }}-deletetask-todo-microservice
            image: k8acrregistry{{ .Release.Name }}.azurecr.io/deletetasktodo:latest
            ports:
              - containerPort: {{ .Values.deletetask.targetPort }}
            env:
              - name: CONNECTION_STRING
                value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:{{ .Release.Name }}k8sqlserverc.database.windows.net,1433;Database=k8db;Uid=sqladmin;Pwd=Password@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"                                          
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "250m"
                memory: "256Mi" 