apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-deletetask-todo-microservice-service
  labels:
    app: {{ .Values.environment }}-deletetask-todo-microservice
spec:
  selector:
    app: {{ .Values.environment }}-deletetask-todo-microservice
  ports:
  - port: {{ .Values.deletetask.port }}
    targetPort: {{ .Values.deletetask.targetPort }}
  type: ClusterIP
