apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.environment }}-microtodo-ui-pod
  labels:
    app: {{ .Values.environment }}-microtodo-ui
spec:
   replicas: {{ .Values.microtodoui.replicas }}
   selector:
     matchLabels:
        app: {{ .Values.environment }}-microtodo-ui
   template:
     metadata:
       labels:
         app: {{ .Values.environment }}-microtodo-ui
     spec:
       containers:
         - name: {{ .Values.environment }}-microtodo-ui
           image: k8acrregistry{{ .Values.environment }}.azurecr.io/microtodoui:latest
           ports:
             - containerPort: {{ .Values.microtodoui.port }}
           resources:
             requests:
               cpu: "100m"
               memory: "128Mi"
             limits:
               cpu: "250m"
               memory: "256Mi"