apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-microtodo-ui-service
  labels:
    app: {{ .Values.environment }}-microtodo-ui
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.environment }}-microtodo-ui
  ports:
    - protocol: TCP
      port: {{ .Values.microtodoui.port }}
      targetPort: {{ .Values.microtodoui.targetPort }}