apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-addtask-todo-microservice-pod
  labels:
    app: {{ .Release.Name }}-addtask-todo-microservice
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-addtask-todo-microservice
  replicas: {{ .Values.addtask.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-addtask-todo-microservice
    spec:
      containers:
      - name: {{ .Release.Name }}-addtask-todo-microservice
        image: k8acrregistry{{ .Values.environment }}.azurecr.io/{{ .Values.addtask.imagename }}:{{ .Values.addtask.imageversion }}
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:{{ .Values.environment }}k8sqlserverc.database.windows.net,1433;Database={{ .Values.environment }}k8db;Uid=sqladmin;Pwd=Password@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.addtask.targetPort }}

