environment: dev
createService: true
createIstioResources: true
serviceactive: blue 


keyvault:
  tenantId: "90d26b91-2a7d-4998-a059-54dd93adebf6"  # Your tenant ID

managedIdentity:
  clientId: "eda7c3ea-346a-457b-a524-91a0c062bd86"  # From az identity list output

ingress: 
  host: microtodo-ui.tangi.fun


microtodoui:
  port: 80
  targetPort: 80
  replicas: 1
  imagename: microtodoui
  imageversion: latest
gettask:
  port: 80
  targetPort: 8000
  replicas: 1
  imagename: gettaskstodo
  imageversion: latest
deletetask:
  port: 80
  targetPort: 8000
  replicas: 1
  imagename: deletetasktodo
  imageversion: latest
addtask:
  port: 80
  targetPort: 8000
  replicas: 1
  imagename: addaaskaodo
  imageversion: latest