name: K8 Todo Infra workflow

on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment Name'
        required: true
        type: choice
        options:
          - 'dev'
          - 'qa'
          - 'prod'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: k8 infrastructure deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: az login using federated credentials
        uses: azure/login@v1
        with:
          client-id: "23604f03-61da-4f4c-a41e-76f2b84f5e09"
          tenant-id: "90d26b91-2a7d-4998-a059-54dd93adebf6"
          subscription-id: "651a708a-a61f-48a6-8006-0d3a0036a680"

      - name: Terraform Init
        working-directory: ./Infrastructure/root_module_k8s
        env:
          ARM_CLIENT_ID: "23604f03-61da-4f4c-a41e-76f2b84f5e09"
          ARM_TENANT_ID: "90d26b91-2a7d-4998-a059-54dd93adebf6"
          ARM_SUBSCRIPTION_ID: "651a708a-a61f-48a6-8006-0d3a0036a680"
          ARM_USE_OIDC: true
        run: terraform init -backend-config="key=${{ github.event.inputs.env }}-todoapp.tfstate"


      - name: Terraform fmt
        working-directory: ./Infrastructure/root_module_k8s
        run: terraform fmt --recursive
        env:
          ARM_CLIENT_ID: "23604f03-61da-4f4c-a41e-76f2b84f5e09"
          ARM_TENANT_ID: "90d26b91-2a7d-4998-a059-54dd93adebf6"
          ARM_SUBSCRIPTION_ID: "651a708a-a61f-48a6-8006-0d3a0036a680"
          ARM_USE_OIDC: true

      - name: Terraform plan
        working-directory: ./Infrastructure/root_module_k8s
        run: terraform plan --var-file=${{ github.event.inputs.env}}_terraform.tfvars
        env:
          ARM_CLIENT_ID: "23604f03-61da-4f4c-a41e-76f2b84f5e09"
          ARM_TENANT_ID: "90d26b91-2a7d-4998-a059-54dd93adebf6"
          ARM_SUBSCRIPTION_ID: "651a708a-a61f-48a6-8006-0d3a0036a680"
          ARM_USE_OIDC: true

      - name: Terraform Apply
        working-directory: ./Infrastructure/root_module_k8s
        run: terraform apply --var-file=${{ github.event.inputs.env}}_terraform.tfvars -auto-approve
        env:
          ARM_CLIENT_ID: "23604f03-61da-4f4c-a41e-76f2b84f5e09"
          ARM_TENANT_ID: "90d26b91-2a7d-4998-a059-54dd93adebf6"
          ARM_SUBSCRIPTION_ID: "651a708a-a61f-48a6-8006-0d3a0036a680"
          ARM_USE_OIDC: true
      